=== xplat/mxt/mxt/test/odds/Odds_XML.dtd
<!ELEMENT XML_File_ID (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT sport (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Line_Time (#PCDATA)>
<!ELEMENT Notes (#PCDATA)>
<!ELEMENT GameID (#PCDATA)>
<!ELEMENT Game_Date (#PCDATA)>
<!ELEMENT Game_Time (#PCDATA)>
<!ELEMENT AwayTeamID (#PCDATA)>
<!ELEMENT AwayRotationNumber (#PCDATA)>
<!ELEMENT AwayAbbr (#PCDATA)>
<!ELEMENT AwayTeamName (#PCDATA)>
<!ELEMENT Casino (#PCDATA)>
<!ELEMENT AwayTeam ( ( AwayTeamID, AwayRotationNumber, AwayAbbr, AwayTeamName, Casino* ) )>
<!ELEMENT HomeTeamID (#PCDATA)>
<!ELEMENT HomeRotationNumber (#PCDATA)>
<!ELEMENT HomeAbbr (#PCDATA)>
<!ELEMENT HomeTeamName (#PCDATA)>
<!ELEMENT HomeTeam ( ( HomeTeamID, HomeRotationNumber, HomeAbbr, HomeTeamName, Casino* ) )>
<!ELEMENT Over_Under ( Casino* )>
<!ELEMENT Game ( ( GameID, Game_Date, Game_Time, AwayTeam, HomeTeam, Over_Under ) )>
<!ELEMENT time_stamp (#PCDATA)>

<!--
The generated message schema is too general; it allows any number
of anything in any order. We know that the first couple of elements
are required and appear in a fixed order.
-->
<!--
Warning: the TSN DTD suggests the existence of an optional League_Name
element that would appear next to the Notes*.
-->
<!ELEMENT message ( XML_File_ID, heading, category, sport, Title, Line_Time, ( Notes*, Game+)*, time_stamp )>

<!ATTLIST Casino ClientID CDATA #REQUIRED>
<!ATTLIST Casino Name CDATA #REQUIRED>

=== xplat/mxt/mxt/test/odds/odds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE message PUBLIC "-//TSN//DTD Statistics 1.0/EN" "Odds_XML.dtd">
<message>
  <XML_File_ID>20109207</XML_File_ID>
  <heading>AEO;CBB-ODDS</heading>
  <category>Odds</category>
  <sport>CBASK</sport>
  <Title>Las Vegas College Basketball Line</Title>
  <Line_Time>Current Line as of 10:30 A.M. ET</Line_Time>
  <Game>
    <GameID>70290</GameID>
    <Game_Date>01/11/2014</Game_Date>
    <Game_Time>11:00 AM</Game_Time>
    <AwayTeam>
      <AwayTeamID>C45</AwayTeamID>
      <AwayRotationNumber>519</AwayRotationNumber>
      <AwayAbbr>STLOUIS</AwayAbbr>
      <AwayTeamName>Saint Louis</AwayTeamName>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </AwayTeam>
    <HomeTeam>
      <HomeTeamID>A69</HomeTeamID>
      <HomeRotationNumber>520</HomeRotationNumber>
      <HomeAbbr>DAYTON</HomeAbbr>
      <HomeTeamName>Dayton</HomeTeamName>
      <Casino ClientID="116" Name="5Dimes">-2</Casino>
      <Casino ClientID="111" Name="Sports Interaction">-2.5</Casino>
      <Casino ClientID="104" Name="BOVADA">-2</Casino>
      <Casino ClientID="121" Name="Mirage">-2</Casino>
      <Casino ClientID="127" Name="DonBest Consensus">-2</Casino>
    </HomeTeam>
    <Over_Under>
      <Casino ClientID="116" Name="5Dimes">132.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">132.5</Casino>
      <Casino ClientID="104" Name="BOVADA">133</Casino>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus">132.5</Casino>
    </Over_Under>
  </Game>
  <Game>
    <GameID>68084</GameID>
    <Game_Date>01/11/2014</Game_Date>
    <Game_Time>12:00 PM</Game_Time>
    <AwayTeam>
      <AwayTeamID>B22</AwayTeamID>
      <AwayRotationNumber>521</AwayRotationNumber>
      <AwayAbbr>INDIANA</AwayAbbr>
      <AwayTeamName>Indiana</AwayTeamName>
      <Casino ClientID="116" Name="5Dimes">-1.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">-1.5</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage">-1.5</Casino>
      <Casino ClientID="127" Name="DonBest Consensus">-1.5</Casino>
    </AwayTeam>
    <HomeTeam>
      <HomeTeamID>C21</HomeTeamID>
      <HomeRotationNumber>522</HomeRotationNumber>
      <HomeAbbr>PENNST</HomeAbbr>
      <HomeTeamName>Penn State</HomeTeamName>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </HomeTeam>
    <Over_Under>
      <Casino ClientID="116" Name="5Dimes">148.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">148.5</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus">148.5</Casino>
    </Over_Under>
  </Game>
  <Game>
    <GameID>67951</GameID>
    <Game_Date>01/11/2014</Game_Date>
    <Game_Time>12:00 PM</Game_Time>
    <AwayTeam>
      <AwayTeamID>D10</AwayTeamID>
      <AwayRotationNumber>523</AwayRotationNumber>
      <AwayAbbr>WAKEFOREST</AwayAbbr>
      <AwayTeamName>Wake Forest</AwayTeamName>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </AwayTeam>
    <HomeTeam>
      <HomeTeamID>C23</HomeTeamID>
      <HomeRotationNumber>524</HomeRotationNumber>
      <HomeAbbr>PITT</HomeAbbr>
      <HomeTeamName>Pittsburgh</HomeTeamName>
      <Casino ClientID="116" Name="5Dimes">-14.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">-14.5</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage">-14</Casino>
      <Casino ClientID="127" Name="DonBest Consensus">-15</Casino>
    </HomeTeam>
    <Over_Under>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </Over_Under>
  </Game>
  <Game>
    <GameID>67812</GameID>
    <Game_Date>01/11/2014</Game_Date>
    <Game_Time>12:00 PM</Game_Time>
    <AwayTeam>
      <AwayTeamID>C09</AwayTeamID>
      <AwayRotationNumber>525</AwayRotationNumber>
      <AwayAbbr>NOTREDAME</AwayAbbr>
      <AwayTeamName>Notre Dame</AwayTeamName>
      <Casino ClientID="116" Name="5Dimes">-1.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">-1</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage">-1</Casino>
      <Casino ClientID="127" Name="DonBest Consensus">-1.5</Casino>
    </AwayTeam>
    <HomeTeam>
      <HomeTeamID>B05</HomeTeamID>
      <HomeRotationNumber>526</HomeRotationNumber>
      <HomeAbbr>GATECH</HomeAbbr>
      <HomeTeamName>Georgia Tech</HomeTeamName>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </HomeTeam>
    <Over_Under>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </Over_Under>
  </Game>
  <Game>
    <GameID>67708</GameID>
    <Game_Date>01/11/2014</Game_Date>
    <Game_Time>12:00 PM</Game_Time>
    <AwayTeam>
      <AwayTeamID>A27</AwayTeamID>
      <AwayRotationNumber>527</AwayRotationNumber>
      <AwayAbbr>BOSTONCOLL</AwayAbbr>
      <AwayTeamName>Boston College</AwayTeamName>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </AwayTeam>
    <HomeTeam>
      <HomeTeamID>D08</HomeTeamID>
      <HomeRotationNumber>528</HomeRotationNumber>
      <HomeAbbr>VATECH</HomeAbbr>
      <HomeTeamName>Virginia Tech</HomeTeamName>
      <Casino ClientID="116" Name="5Dimes">-2</Casino>
      <Casino ClientID="111" Name="Sports Interaction">-2</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage">-2.5</Casino>
      <Casino ClientID="127" Name="DonBest Consensus">-2</Casino>
    </HomeTeam>
    <Over_Under>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </Over_Under>
  </Game>
  <Game>
    <GameID>67900</GameID>
    <Game_Date>01/11/2014</Game_Date>
    <Game_Time>12:00 PM</Game_Time>
    <AwayTeam>
      <AwayTeamID>B95</AwayTeamID>
      <AwayRotationNumber>529</AwayRotationNumber>
      <AwayAbbr>NCAROLINA</AwayAbbr>
      <AwayTeamName>North Carolina</AwayTeamName>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </AwayTeam>
    <HomeTeam>
      <HomeTeamID>C76</HomeTeamID>
      <HomeRotationNumber>530</HomeRotationNumber>
      <HomeAbbr>SYRACUSE</HomeAbbr>
      <HomeTeamName>Syracuse</HomeTeamName>
      <Casino ClientID="116" Name="5Dimes">-8</Casino>
      <Casino ClientID="111" Name="Sports Interaction">-8.5</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage">-7.5</Casino>
      <Casino ClientID="127" Name="DonBest Consensus">-8.5</Casino>
    </HomeTeam>
    <Over_Under>
      <Casino ClientID="116" Name="5Dimes">137.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">137.5</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus">137.5</Casino>
    </Over_Under>
  </Game>
  <Game>
    <GameID>68057</GameID>
    <Game_Date>01/11/2014</Game_Date>
    <Game_Time>12:00 PM</Game_Time>
    <AwayTeam>
      <AwayTeamID>B28</AwayTeamID>
      <AwayRotationNumber>531</AwayRotationNumber>
      <AwayAbbr>IOWAST</AwayAbbr>
      <AwayTeamName>Iowa State</AwayTeamName>
      <Casino ClientID="116" Name="5Dimes">-4.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">-4</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage">-3</Casino>
      <Casino ClientID="127" Name="DonBest Consensus">-4.5</Casino>
    </AwayTeam>
    <HomeTeam>
      <HomeTeamID>C13</HomeTeamID>
      <HomeRotationNumber>532</HomeRotationNumber>
      <HomeAbbr>OKLAHOMA</HomeAbbr>
      <HomeTeamName>Oklahoma</HomeTeamName>
      <Casino ClientID="116" Name="5Dimes"/>
      <Casino ClientID="111" Name="Sports Interaction"/>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus"/>
    </HomeTeam>
    <Over_Under>
      <Casino ClientID="116" Name="5Dimes">171.5</Casino>
      <Casino ClientID="111" Name="Sports Interaction">171</Casino>
      <Casino ClientID="104" Name="BOVADA"/>
      <Casino ClientID="121" Name="Mirage"/>
      <Casino ClientID="127" Name="DonBest Consensus">171.5</Casino>
    </Over_Under>
  </Game>
  <Game>
    <GameID>70794</GameID>
    <Game_Date>01/11/2014</Game_Date>
